name: TODO

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "**"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    outputs:
      tag: ${{ steps.meta.outputs.tags }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up QEMU # TODO needed?
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v4
        with:
          context: ${{ inputs.directory }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  directories:
    runs-on: ubuntu-latest
    name: Enumerate tests
    outputs:
      tests-list: ${{ steps.set-dirs.outputs.dir }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - id: set-dirs
        run: |
          echo "dir=$(test/test.sh --list-tests-json)" >> $GITHUB_OUTPUT

  test:
    runs-on: ubuntu-latest
    needs: [directories, build]
    strategy:
      matrix:
        testname: ${{fromJson(needs.directories.outputs.tests-list)}}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Update submodules
        run: git submodule update --init
      - name: Run test ${{matrix.testname}}
        env:
          IMAGE: ${{ needs.build.outputs.tag }}
        run: |
          test/test.sh ${{matrix.testname}}

  publish:
    runs-on: ubuntu-latest
    needs: [build, test]
    if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    steps:
      - name: Push as 'latest'
        run: |
          docker image pull ${{ needs.build.outputs.tag }}
          docker image tag ${{ needs.build.outputs.tag }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          docker image push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
